### ISSUE TITLE
Add path as command line option

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [poach3r/pywal-obsidianmd#1]
I think that adding the Obsidian vault path as command line option would be an essential part to make scripting easier.

**Comment by stefanpinterBE** [comment]
i forked it and created a pull request for that :)

my fork has it:
https://github.com/stefanpinterBE/pywal-obsidianmd

**Comment by poach3r** [comment]
This has been added thanks to stefanpinterBE.

**Comment by agenttank** [comment]
hi! 

thanks for merging :)
your readme.md now says, that it is a fork though
